################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
SRC_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
SECONDARY_SIZE := 
COMPILED_SRCS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
code \
libraries/infineon_libraries/Infra/Platform/Tricore/Compilers \
libraries/infineon_libraries/Service/CpuGeneric/If \
libraries/infineon_libraries/Service/CpuGeneric/StdIf \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Bsp \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Comm \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/General \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Math \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Time \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Asc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Lin \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Spi \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Icu \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/PwmBc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/PwmHl \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/TPwm \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Timer \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/TimerWithTrigger \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Cif/Cam \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Cif/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/CStart \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Irq \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Trap \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Dma/Dma \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Dma/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Dsadc/Dsadc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Dsadc/Rdc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Dsadc/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Dts/Dts \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Dts/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Emem/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Eray/Eray \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Eray/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Eth/Phy_Pef7071 \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Eth/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Fce/Crc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Fce/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Fft/Fft \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Fft/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Flash/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gpt12/IncrEnc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gpt12/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/Pwm \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/PwmHl \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/Timer \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tim/In \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tom/Pwm \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tom/PwmHl \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tom/Timer \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Trig \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Hssl/Hssl \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Hssl/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/I2c/I2c \
libraries/infineon_libraries/iLLD/TC26B/Tricore/I2c/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Iom/Driver \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Iom/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Msc/Msc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Msc/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Mtu/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Multican/Can \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Multican/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Port/Io \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Port/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5/Psi5 \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5s/Psi5s \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5s/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/SpiMaster \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/SpiSlave \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Scu/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Sent/Sent \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Sent/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Smu/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Src/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Stm/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Stm/Timer \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Vadc/Adc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Vadc/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/_Impl \
libraries/infineon_libraries/iLLD/TC26B/Tricore/_Lib/DataHandling \
libraries/infineon_libraries/iLLD/TC26B/Tricore/_Lib/InternalMux \
libraries/infineon_libraries/iLLD/TC26B/Tricore/_PinMap \
libraries/zf_common \
libraries/zf_device \
libraries/zf_driver \
user \

